musicat/api/urls.py
from django.conf.urls import url

from api import views

urlpatterns = [
    url(r'^songs/$', views.ListSongs.as_view(), name='list_songs'),
    url(r'^groups/$', views.GroupList.as_view(), name='list_groups'),
]

musicat/musicat/urls.py
from django.conf import settings
from django.conf.urls import include, url, static
from django.contrib import admin


urlpatterns = [
    url(r'^songs/', include('songs.urls', namespace='songs')),
    url(r'^user/', include('users.urls', namespace='users')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('common.urls', namespace='common')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

musicat/songs/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.SongIndexView.as_view(), name='index'),
    url(r'^newsong/$', views.RegisterSongView.as_view(), name='register'),
    url(r'^update/(?P<request_key>\w+)/$', views.update_register, name='update_register'),
    url(r'^group/(?P<sign>\w)/$', views.update_register, name='update_register'),
    url(r'^(?P<slug>[-\w]*)/post/$', views.poster, name='poster'),
    url(r'^(?P<slug>[-\w]*)/deletesong/$', views.delete_song, name='delete_song'),
    url(r'^(?P<slug>[-\w]*)/registrado/$', views.registered, name='registered'),

    url(r'^(?P<pk_or_slug>[-\w]*)/$', views.song_detail_view, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.song_detail_view, name='detail_by_pk'),
]

musicat/songs/models.py
import hashlib

from django.core.urlresolvers import reverse
from django.db import models
from django.utils.text import slugify

from autoslug import AutoSlugField
from django_extensions.db.models import TimeStampedModel

from users.models import OwnerProfile


class SongQuerySet(models.QuerySet):

    def __str__(self):
        return self.name


class Group(models.Model):
    name = models.TextField(max_length=100, primary_key=True)
    genre = models.TextField(max_length=100)
    image = models.ImageField(upload_to='group_photos')

    def __str__(self):
        return self.name


def get_slug(instance):
    group = ''
    if instance.group:
        group = instance.group.name
    return slugify('{}-{}'.format(instance.name, group))


class Song(models.Model):
    owner = models.ForeignKey(OwnerProfile)
    group = models.ForeignKey(Group)
    #group = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=5000)
    #objects = SongQuerySet.as_manager()

    def get_absolute_url(self):
        return reverse('songs:detail', kwargs={'pk_or_slug': id})

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-id']

# CREATE TABLE test_songs (id int, song_name VARCHAR(50), group_name VARCHAR(50), song_text VARCHAR(2000),


# class Songs(models.Model):
#     song_name = models.CharField(max_length=50)
#     group_name = models.CharField(max_length=50)
#     song_text = models.CharField(max_length=2000)
#     song_accords = models.CharField(max_length=100)

# CREATE TABLE test_groups (id INT, group_name VARCHAR(50), genre VARCHAR(50), group_members VARCHAR(200),
# image_url VARCHAR(250), description VARCHAR(500));

# class Groups(models.Model):
    #     group_name = models.CharField(max_length=50)
    #     genre = models.CharField(max_length=50)
    #     group_members = models.CharField(max_length=50)
    #     image_url = models.CharField(max_length=50)
    #     description = models.CharField(max_length=500)

musicat/songs/forms.py
from django import forms
from django.utils.translation import ugettext as _


from songs import models

# class SongForm(forms.ModelForm):
#     def __init__(self, *args, **kwargs):
#         initial = kwargs.pop('initial', {})
#         kwargs['initial'] = initial
#         super(SongForm, self).__init__(*args, **kwargs)
#
#     class Meta:
#         model = models.Song
#         fields = ('name', 'group', 'description',
#                   'owner',)
#         widgets = {
#             'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('Выхода нет')}),
#             'group': forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('Сплин')}),
#             'description': forms.Textarea(attrs={'class': 'form-control',
#                                                  'placeholder': _(
#                                                      "Скоро рассвет,\n"
#                                                      "Выхода нет. \n"
#                                                      "Ключ поверни...")}),
#         }


class SongForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(SongForm, self).__init__(*args, **kwargs)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('Выхода нет')}),
            'group': forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('Сплин')}),
            'description': forms.Textarea(attrs={'class': 'form-control',
                                                 'placeholder': _(
                                                     "Скоро рассвет,\n"
                                                     "Выхода нет. \n"
                                                     "Ключ поверни...")}),
        }
        self.fields['name'].widget = widgets['name']
        self.fields['group'].widget = widgets['group']
        # self.fields['description'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget = widgets['description']
    class Meta:
        model = models.Song
        fields = ('name', 'group', 'description',)

    def save(self, commit=True):
        song = super(SongForm, self).save(commit=False)
        if commit:
            song.save()
        return song


    def clean_name(self):
        return self.cleaned_data['name'].title()


class SearchForm(forms.Form):
    
    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)

    def clean(self):

        cleaned_data = super(SearchForm, self).clean()

        if not any([cleaned_data['name'],
                    cleaned_data['group'],
                    cleaned_data['description']]):
            raise forms.ValidationError(_('You must select at least one filter'))

musicat/songs/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.utils.translation import pgettext, ugettext as _
from django.views.decorators.http import require_POST
from django.views.generic import ListView, CreateView, \
    UpdateView, View

from songs import forms, models


class SongIndexView(ListView):
    template_name = 'songs/index.html'
    context_object_name = 'songs'

    def get_queryset(self):
        return models.Song.objects.select_related('group').order_by('-id')[:12]


def song_detail_view(request, pk_or_slug):
    song = models.Song.objects.filter(id=pk_or_slug).first()

    if not song:
        try:
            song = models.Song.objects.get(id=pk_or_slug)
        except ValueError:
            raise Http404()

    context = {
        'song': song,
        'current_url': request.build_absolute_uri(request.get_full_path()),
    }
    return render(request, 'songs/song_detail.html', context)


def paginate_songs(queryset, page, paginate_by=12):
    """Returns the Songs for the current requested page and the page number"""
    paginator = Paginator(queryset, paginate_by)

    try:
        songs = paginator.page(page)
        page = int(page)
    except PageNotAnInteger:
        songs = paginator.page(1)
        page = 1
    except EmptyPage:
        songs = paginator.page(paginator.num_pages)
        page = paginator.num_pages

    return songs, page


def render_song_list(request, queryset):
    songs, page = paginate_songs(queryset, request.GET.get('page'))

    return render(request, 'songs/song_list.html', {
        'songs': songs,
        'current_page': page
    })


class RegisterSongView(LoginRequiredMixin, CreateView):
    template_name = 'songs/addSong.html'
    model = models.Song
    form_class = forms.SongForm

    def get_success_url(self):
        return reverse('songs:registered', args=[self.object.id])

    def get(self, request, *args, **kwargs):
        if not request.user.is_information_confirmed:
            messages.warning(request, _('Please confirm your informations before registering a new song.'))
            return HttpResponseRedirect(reverse('users:edit'))
        else:
            return super(RegisterSongView, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(RegisterSongView, self).form_valid(form)


@require_POST
def delete_song(request, slug):
    song = get_object_or_404(models.Song, slug=slug)

    if request.user == song.owner:
        song.delete()
        return HttpResponseRedirect(reverse('songs:index'))

    return HttpResponseRedirect(song.get_absolute_url())


class SearchView(View):

    def get(self, request):
        return render(request, 'songs/search.html', {'form': SearchForm()})

    def post(self, request):
        form = SearchForm(request.POST)

        if not form.is_valid():
            return render(request, 'songs/search.html', {'form': form})

        query = self._build_query(form.cleaned_data)

        songs = models.Song.objects.actives().filter(query)
        return render(request, 'songs/search.html', {'form': form, 'songs': songs})

    @staticmethod
    def _build_query(cleaned_data):
        query = Q()

        for key, value in cleaned_data.items():
            if value:
                query &= Q(**{key: value})

        return query


def registered(request, slug):
    context = {
        'song_slug': slug,
    }
    return render(request, 'songs/registered.html', context)


def poster(request, slug):
    song = get_object_or_404(models.Song, slug=slug)
    return render(request, 'songs/post.html', {'song': song})


def update_register(request, request_key):
    song = get_object_or_404(models.Song, request_key=request_key)
    song.activate()
    return HttpResponseRedirect(song.get_absolute_url())

musicat/songs/templates/songs/addSong.html
{% extends '_layouts/main.html' %}

{% block title %}
<div class="heading">
  <h3 class="title-text text-center">Добавляем песенку</h3>
</div>
{% endblock %}

{% block content %}
  <div class="row">
    {% include 'songs/trackForm.html' %}
  </div>
{% endblock %}

musicat/songs/templates/songs/detail.html
{% extends '_layouts/main.html' %}
{% load static thumbnail %}

{% block title %}{{ song.name }}{% endblock %}
{% block page_title %}{{ song.name|title }}, {{ song.group|title }}{% endblock %}

{% block content %}
  <div class="modal fade" id="delete_song" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Delete Track</h4>
        </div>

        <div class="modal-body">
          <p>Do you really want to erase?</p>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>

          <form action="{% url 'songs:delete_song' song.slug %}" method="post" class="form-inline">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete"/>
          </form>
        </div>

      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-5">
      <a href="{{ song.profile_picture.url }}" data-lightbox="{{ song.slug }}" data-title="{{ song }}">
        <img class="img-thumbnail" src="{{ song.profile_picture|thumbnail_url:'song_thumb' }}"
             alt="{{ song }}"/>
      </a>
      {% if user == song.owner %}
        <form class="form-horizontal" method="POST" enctype="multipart/form-data"
              action="{% url 'songs:upload_image' song.slug %}">
          {% csrf_token %}
          <input name="song_id" value="{{ song.id }}" type="hidden">

          <div class="form-group">
            <label for="another_picture" class="control-label">Add Photo</label>
            <input type="file" id="another_picture" name="another_picture">
            <span class="help-block">Maximum image size is 8MB</span>
          </div>
          <div class="form-group">
            <input type="submit" name="submit" class="btn btn-primary pull-right" value="Submit Image}">
          </div>
        </form>
      {% endif %}
    </div>

    <div class="col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">
          <p>
            <strong>Description:</strong><br/>
            {{ song.description }}
          </p>

          <p>
            <strong>City:</strong><br/>
            {{ song.city|title }}
          </p>

          {% if song.size %}
            <p>
              <strong>Size:</strong><br/>
              {{ song.get_size_display }}
            </p>
          {% endif %}

          {% if song.sex %}
            <p>
              <strong>Sex:</strong><br/>
              {{ song.get_sex_display }}
            </p>
          {% endif %}

          {% if user == song.owner %}
            <div class="pull-right">
              {% if not song.found_or_adopted %}
                <form action="{% url 'songs:change_status' song.slug %}" method="post" class="form-inline">
                  {% csrf_token %}
                  <input type="submit" class="btn btn-success" value="
                    {% if song.status == song.MISSING %}
                      {% trans 'Mark as found!' %}
                    {% else %}
                      {% trans 'Mark as adopted!' %}
                    {% endif %}
                  "/>
                </form>
              {% endif %}

              <a href="{% url 'songs:edit' song.slug %}" class="btn btn-primary">{% trans 'Edit' %}</a>

              <a href="{% url 'songs:poster' song.slug %}" class="btn btn-primary">{% trans 'Generate Poster' %}</a>

              <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete_song">
                {% trans 'Delete Pet' %}
              </button>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
    {% if song.photo_set.all %}
      <div class="col-md-12">
        <h3>{% trans 'More photos' %}</h3>

        <div class="row">
          {% for photo in song.photo_set.all %}
            <div class="col-md-3">
              <a href="{{ photo.image.url }}" data-lightbox="{{ song.slug }}" data-title="{{ song }}">
                <img class="img-thumbnail" src="{{ photo.image|thumbnail_url:'song_thumb' }}"
                     alt="{{ song }}"/>
              </a>
            </div>
            {% if forloop.counter|divisibleby:4 %}
              </div>
              <div class="row">
            {% endif %}
          {% endfor %}
          </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

musicat/songs/templates/songs/edit.html
{% extends '_layouts/main.html' %}

{% block title %}
<div class="heading">
  <h3 class="title-text text-center">Edit Track</h3>
</div>
{% endblock %}

{% block content %}
  <div class="row">
    {% include 'songs/trackForm.html' %}
  </div>
{% endblock %}

musicat/songs/templates/songs/index.html
{% extends '_layouts/main.html' %}

{% block title %}<div class="heading">
  <h3 class="title-text text-center">Группы</h3>
</div>
{% endblock %}

{% block body %}
<!--
<ul>
    {% for label in labelsList %}
  <li>
    <a href="{{ label.get_absolute_url }}">
      {{ label.headline}}
    </a>
  <li>
{% endfor %}
</ul>
-->

<div class="labels">
<ul>
  <li><a href="/songs/0/">0</a></li>
  <li><a href="/songs/1/">1</a></li>
  <li><a href="/songs/2/">2</a></li>
  <li><a href="/songs/3/">3</a></li>
  <li><a href="/songs/4/">4</a></li>
  <li><a href="/songs/5/">5</a></li>
  <li><a href="/songs/6/">6</a></li>
  <li><a href="/songs/7/">7</a></li>
  <li><a href="/songs/8/">8</a></li>
  <li><a href="/songs/9/">9</a></li>
  <li><a href="/songs/a/">A</a></li>
  <li><a href="/songs/b/">B</a></li>
  <li><a href="/songs/c/">C</a></li>
  <li><a href="/songs/d/">D</a></li>
  <li><a href="/songs/e/">E</a></li>
  <li><a href="/songs/f/">F</a></li>
  <li><a href="/songs/g/">G</a></li>
  <li><a href="/songs/h/">H</a></li>
  <li><a href="/songs/i/">I</a></li>
  <li><a href="/songs/j/">J</a></li>
  <li><a href="/songs/k/">K</a></li>
  <li><a href="/songs/l/">L</a></li>
  <li><a href="/songs/m/">M</a></li>
  <li><a href="/songs/n/">N</a></li>
  <li><a href="/songs/o/">O</a></li>
  <li><a href="/songs/p/">P</a></li>
  <li><a href="/songs/q/">Q</a></li>
  <li><a href="/songs/r/">R</a></li>
  <li><a href="/songs/s/">S</a></li>
  <li><a href="/songs/t/">T</a></li>
  <li><a href="/songs/u/">U</a></li>
  <li><a href="/songs/v/">V</a></li>
  <li><a href="/songs/w/">W</a></li>
  <li><a href="/songs/x/">X</a></li>
  <li><a href="/songs/y/">Y</a></li>
  <li><a href="/songs/z/">Z</a></li>
</ul>
</div>
{% block content %}
  {% include '_partials/tracksList.html' %}
{% endblock %}
{% endblock body %}

musicat/songs/templates/songs/post.html
{% extends '_layouts/main.html' %}
{% load i18n static thumbnail %}

{% block page %}
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="text-center hidden-print">
          <a onclick="window.print()" class="btn btn-primary">{% trans 'Print' %} <i class="fa fa-print"></i></a>
        </div>

        <div class="page">
          <div class="pull-left print-logo">
            <img class="img-responsive" src="{% static 'img/logo.png' %}" alt="Logo Cadê meu Bicho">
          </div>
          <div class="pull-right print-logo">
            <img class="img-responsive" src="{% static 'img/logo.png' %}" alt="Logo Cadê meu Bicho">
          </div>

          <h1 class="text-center text-uppercase poster-headline">
            {{ song.get_status_display }}
          </h1>

          <div class="text-center">
            <img class="img-responsive img-rounded img-thumbnail"
                 src="{{ song.profile_picture|thumbnail_url:'song_poster' }}"
                 alt="{{ song.name }}">
          </div>

          <h2 class="text-center poster-headline">
            {{ song.name }}
          </h2>

          {% if song.size and song.sex %}
            <h2 class="text-center poster-subheadline">
              {% trans 'Size' %} {{ song.get_size_display|lower }}, {{ song.get_sex_display|lower }}
            </h2>
          {% endif %}

          <p class="font-1_8rem">{{ song.description }}</p>

          <h3>{% trans 'Contact' %}</h3>

          <ul class="list-unstyled font-1_8rem">
            <li>
              {% trans 'Email' %} <i class="fa fa-envelope"></i>: {{ song.owner.email }}
            </li>
            {% if song.owner.phone %}
              <li>
                {% trans 'Phone' %} <i class="fa fa-phone"></i>: {{ song.owner.phone }}
              </li>
            {% endif %}
          </ul>

          <div class="pull-right">
            <p class="font-1_8rem">{% trans 'Visit:' %} www.cademeubicho.com</p>
          </div>
        </div>

      </div>
    </div>
  </div>
{% endblock %}

musicat/songs/templates/songs/registered.html
{% extends '_layouts/main.html' %}
{% load i18n static %}

{% block title %}{% trans 'Registered Pet' %}{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-9">

      <h2>Поздравляю, котик!</h2>

      <!--<p>Para visualizar o cadastro clique <a href="{% url 'songs:detail' %}">жмяк</a>.</p>-->

      <p>
        Ты справился с этим заданием, даже несмотря на то, что у тебя лапки.</p>

      <p>Надеемся что ты добавишь ещё пару песенок, мур :3</p>

      <i class="c-red fa fa-heart"></i></p>
    </div>
  </div>
{% endblock %}

musicat/songs/templates/songs/search.html
{% extends '_layouts/main.html' %}
{% load i18n thumbnail %}

{% block title %}{% trans 'Search' %}{% endblock %}

{% block body %}
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-12">
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger" role="alert">{{ error }}</div>
        {% endfor %}
        <form class="form-inline" action="" method="post">
          {% csrf_token %}

          <div class="form-group">
            <label for="city" class="control-label">{{ form.city.label }}</label>

            {{ form.city }}
          </div>

          <div class="form-group">
            <label for="kind" class="control-label">{{ form.kind.label }}</label>

            {{ form.kind }}
          </div>

          <div class="form-group">
            <label for="status" class="control-label">{{ form.status.label }}</label>

            {{ form.status }}
          </div>

          <div class="form-group">
            <label for="size" class="control-label">{{ form.size.label }}</label>

            {{ form.size }}
          </div>

          <div class="form-group">
            <label for="sex" class="control-label">{{ form.sex.label }}</label>

            {{ form.sex }}
          </div>

          <div class="form-group">
            <input class="btn btn-success" type="submit" value="{% trans 'Search' %}"/>
          </div>
        </form>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <h3>{% trans 'Result' %}</h3>
      </div>
      {% for song in songs %}
        <div class="col-xs-12 col-sm-6 col-md-3 card-song">
          {% include '_partials/song_card.html' with song=song only %}
        </div>
      {% empty %}
        <div class="col-md-12">
          <p>{% trans 'No results' %}</p>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock body %}

musicat/songs/templates/songs/song_detail.html
{% extends '_layouts/base.html' %}
{% load i18n static thumbnail %}

{% block metatags %}
  <meta property="og:title" content="{{ song.name }} | Cadê meu Bicho?">
  <meta property="og:description" content="{{ song.description }}">
  <meta property="og:url" content="{{ current_url }}">
  <meta property="og:site_name" content="Cadê meu Bicho?">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{{ song.name }} | Cadê meu Bicho?">
  <meta name="twitter:description" content="{{ song.description }}">
  <meta name="twitter:image:src"
        content="http://www.cademeubicho.com{{ song.profile_picture|thumbnail_url:'song_thumb' }}">
{% endblock %}

{% block title %}{{ song.name }} - {{ song.get_status_display }}{% endblock %}
{% block page_title %}{{ song.get_status_display }}: {{ song.name|title }}, {{ song.group|title }}{% endblock %}

{% block content %}
  <div class="modal fade" id="delete_song" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">{% trans 'Delete Pet' %}</h4>
        </div>

        <div class="modal-body">
          <p>{% trans 'Do you really want to erase this song?' %}</p>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Cancel' %}</button>

          <form action="{% url 'songs:delete_song' song.slug %}" method="post" class="form-inline">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="{% trans 'Delete' %}"/>
          </form>
        </div>

      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-5">
      <a href="{{ song.profile_picture.url }}" data-lightbox="{{ song.slug }}" data-title="{{ song }}">
        <img class="img-thumbnail" src="{{ song.profile_picture|thumbnail_url:'song_thumb' }}"
             alt="{{ song }}"/>
      </a>
      {% if user == song.owner %}
        <form class="form-horizontal" method="POST" enctype="multipart/form-data"
              action="{% url 'songs:upload_image' song.slug %}">
          {% csrf_token %}
          <input name="song_id" value="{{ song.id }}" type="hidden">

          <div class="form-group">
            <label for="another_picture" class="control-label">{% trans 'Add Photo' %}</label>
            <input type="file" id="another_picture" name="another_picture">
            <span class="help-block">{% trans 'Maximum image size is 8MB' %}</span>
          </div>
          <div class="form-group">
            <input type="submit" name="submit" class="btn btn-primary pull-right" value="{% trans 'Submit Image' %}">
          </div>
        </form>
      {% endif %}
    </div>

    <div class="col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">
          <p>
            <strong>{% trans 'Description' %}:</strong><br/>
            {{ song.description }}
          </p>

          <p>
            <strong>{% trans 'City' %}:</strong><br/>
            {{ song.city|title }}
          </p>

          {% if song.size %}
            <p>
              <strong>{% trans 'Size' %}:</strong><br/>
              {{ song.get_size_display }}
            </p>
          {% endif %}

          {% if song.sex %}
            <p>
              <strong>{% trans 'Sex' %}:</strong><br/>
              {{ song.get_sex_display }}
            </p>
          {% endif %}

          <p>
            <strong>{% trans 'Contact' %}:</strong><br/>
            <a href="{% url 'users:user_profile' song.owner.id %}">{{ song.owner.get_full_name }}</a>
            {% if song.owner.facebook %} | <a href="{{ song.owner.facebook }}">Facebook</a>{% endif %}
          </p>

          <p>
            <strong>{% trans 'Share' %}:</strong><br/>
            <a href="http://www.facebook.com/sharer.php?u={{ current_url }}" target="_blank">
              <img src="{% static 'img/facebook.png' %}" alt="Facebook"/>
            </a>
            <a href="http://twitter.com/share?url={{ current_url }}" target="_blank">
              <img src="{% static 'img/twitter.png' %}" alt="Twitter"/>
            </a>
          </p>
          {% if user == song.owner %}
            <div class="pull-right">
              {% if not song.found_or_adopted %}
                <form action="{% url 'songs:change_status' song.slug %}" method="post" class="form-inline">
                  {% csrf_token %}
                  <input type="submit" class="btn btn-success" value="
                    {% if song.status == song.MISSING %}
                      {% trans 'Mark as found!' %}
                    {% else %}
                      {% trans 'Mark as adopted!' %}
                    {% endif %}
                  "/>
                </form>
              {% endif %}

              <a href="{% url 'songs:edit' song.slug %}" class="btn btn-primary">{% trans 'Edit' %}</a>

              <a href="{% url 'songs:poster' song.slug %}" class="btn btn-primary">{% trans 'Generate Poster' %}</a>

              <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete_song">
                {% trans 'Delete Pet' %}
              </button>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
    {% if song.photo_set.all %}
      <div class="col-md-12">
        <h3>{% trans 'More photos' %}</h3>

        <div class="row">
          {% for photo in song.photo_set.all %}
            <div class="col-md-3">
              <a href="{{ photo.image.url }}" data-lightbox="{{ song.slug }}" data-title="{{ song }}">
                <img class="img-thumbnail" src="{{ photo.image|thumbnail_url:'song_thumb' }}"
                     alt="{{ song }}"/>
              </a>
            </div>
            {% if forloop.counter|divisibleby:4 %}
              </div>
              <div class="row">
            {% endif %}
          {% endfor %}
          </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

musicat/songs/templates/songs/song_list.html
{% extends '_layouts/main.html' %}

{% block title %}{{ kind }} - {{ status }}{% endblock %}

{% block content %}
  {% include '_partials/trackList.html' %}
{% endblock %}

musicat/songs/templates/songs/trackForm.html
{% load thumbnail %}

<form class="form-horizontal" method="POST" enctype="multipart/form-data">
  {% csrf_token %}



  <div class="form-group{% if form.name.errors %} has-error{% endif %}">
    <label for="{{ form.name.id_for_label }}" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      {{ form.name }}
      {{ form.name.errors }}
    </div>
  </div>
  <div class="form-group{% if form.name.errors %} has-error{% endif %}">
    <label for="{{ form.group.id_for_label }}" class="col-sm-2 control-label">Group</label>
    <div class="col-sm-10">
      {{ form.group }}
      {{ form.group.errors }}
    </div>
  </div>
  <div class="form-group{% if form.description.errors %} has-error{% endif %}">
    <label for="{{ form.description.id_for_label }}" class="col-sm-2 control-label">Description</label>

    <div class="col-sm-10">
      {{ form.description }}
      {{ form.description.errors }}
    </div>
  </div>

  <div class="form-group">
    <input type="submit" name="submit" class="btn btn-primary pull-right" value="
    {% if song %}
      Save Changes
    {% else %}
      ADD song
    {% endif %}
    ">
  </div>
</form>